version: '3'

services:
  postgres-bitmask-benchmark:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-${FIXTURES}-fixtures.sql:/docker-entrypoint-initdb.d/dump.sql
